import { useQuery } from "@tanstack/react-query";
import { Alert, Card, Col, List, Row, Space, Statistic, Tag, Typography } from "antd";
import { EmptyState, ErrorState, PageContainer } from "@tsuz/ui";
import { businessHomeQueryKey, loadBusinessHomeSummary } from "../queries/business-home.query";
import { useAppStore } from "../stores/app.store";

export default function BusinessHomePage() {
  const mode = useAppStore((state) => state.mode);
  const appName = useAppStore((state) => state.appName);
  const apiBaseUrl = useAppStore((state) => state.apiBaseUrl);
  const hasAuthBridge = useAppStore((state) => state.hasAuthBridge);
  const currentUser = useAppStore((state) => state.currentUser);
  const query = useQuery({
    queryKey: businessHomeQueryKey(apiBaseUrl, currentUser?.id ?? "guest"),
    queryFn: () => loadBusinessHomeSummary({ apiBaseUrl, currentUser })
  });
  const summary = query.data;

  return (
    <PageContainer
      title="Business home"
      description="Phase 9 starter page with host props, app state, React Query data, browser coverage, CI, and deploy workflow wired together."
      actions={<Tag color={mode === "qiankun" ? "purple" : "blue"}>{mode === "qiankun" ? "qiankun mount" : "standalone"}</Tag>}
    >
      <Space direction="vertical" size="large" className="full-width">
        <Card>
          <Space direction="vertical" size="middle" className="full-width">
            <Typography.Paragraph>
              Generated by Tsu from the <code>mfe-app</code> template. This sub application can run independently on port
              7201 or receive auth and API props from the generated mfe-main host.
            </Typography.Paragraph>
            <Space wrap>
              <Tag color="blue">React</Tag>
              <Tag color="purple">qiankun</Tag>
              <Tag color="green">Phase 9 deploy ready</Tag>
              <Tag color={hasAuthBridge ? "success" : "default"}>Auth bridge: {hasAuthBridge ? "provided" : "standalone"}</Tag>
            </Space>
            <Typography.Text>Application: {appName}</Typography.Text>
            <Typography.Text type="secondary">API base URL: {apiBaseUrl}</Typography.Text>
            <Typography.Text type="secondary">Current user: {currentUser?.name ?? "Standalone visitor"}</Typography.Text>
          </Space>
        </Card>

        {query.isError ? (
          <ErrorState title="Unable to load business summary" description="Replace the demo query with a real backend request when ready." />
        ) : null}

        <Row gutter={[16, 16]}>
          {(summary?.metrics ?? []).map((metric) => (
            <Col xs={24} md={8} key={metric.label}>
              <Card className="metric-card">
                <Statistic title={metric.label} value={metric.value} suffix={metric.suffix} />
                <Tag color={metric.color}>{metric.trend}</Tag>
              </Card>
            </Col>
          ))}
        </Row>

        <Card title="Next business actions" loading={query.isLoading || query.isFetching}>
          {summary ? (
            <List bordered dataSource={summary.nextActions} renderItem={(item) => <List.Item>{item}</List.Item>} />
          ) : (
            <EmptyState title="Loading business summary" description="React Query is preparing deterministic starter data." />
          )}
        </Card>

        <Alert
          type="info"
          showIcon
          message="Template extension point"
          description="Keep backend calls inside query modules and inject host auth through createMfeApiClient for production business features."
        />
      </Space>
    </PageContainer>
  );
}
